# See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "0.11"
install:
  - npm install
before_script:
  - npm run build
  # Firefox addon support
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-ci
after_success:
#  - cat ./coverage/lcov.dat | ./node_modules/coveralls/bin/coveralls.js
  - npm run docs

# Deploy JSDocs to S3 static site.
# See http://docs.travis-ci.com/user/deployment/s3/
deploy:
  provider: s3
  # Access key is the public key.
  access_key_id: AKIAJLMFT7PREEIB7JSQ
  # Secret access key is the private key, encrypted for Travis.
  secret_access_key:
    secure: WKf+D1FEND54BsA1xVK4XsxpF9wXcqXbOHmPBOESqu5Fs7vGYl85ouqkVaZBPdBFKFcKPHHCPP6gNxrcy4xcgtLwhPNDmAfQiyrfTnyJIEQaD0ON1tPvr0D+XF3MSWC9IEqB8fyRLLam782BoCv8fJDBtShdUNoCKw5IreH+PjM=
  bucket: jsdocs.atlas.urbanetic.net
  endpoint: jsdocs.atlascesium.urbanetic.net.s3-website-ap-southeast-2.amazonaws.com
  region: ap-southeast-2
  local-dir: jsdocs
  skip_cleanup: true
  on:
    all_branches: true
#    tags: true
addons:
  firefox: "39.0"

